name: Budowanie i Wdrażanie Apache Docker Compose

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Sklonowanie repozytorium
      uses: actions/checkout@v4

    - name: Zbuduj obraz Dockera # RE-ADD THIS STEP
      run: docker build -t my-apache-ssl .
      # This step must happen BEFORE install.sh tries to use the image

    - name: Nadanie uprawnień do wykonywania skryptowi install.sh
      run: chmod +x ./install.sh

    - name: Uruchomienie skryptu wdrożeniowego Docker Compose
      run: sudo ./install.sh
      shell: bash

    - name: Weryfikacja działania usług Docker Compose
      run: |
      
        echo "Testowanie dostępu HTTPS (curl z hosta):"
        curl -k -s -o /dev/null -w "HTTP Code HTTPS: %{http_code}\n" https://localhost:443/ || true
        # ^ -k (insecure) jest potrzebne dla samopodpisanego certyfikatu
        echo "Lista wszystkich usług Docker Compose:"
        sudo docker compose ps
        echo "Pobieranie logów z usługi Apache:"
        sudo docker compose logs apache --tail 50
        echo "Testowanie dostępu HTTP (curl z hosta):"
        curl -s -o /dev/null -w "HTTP Code: %{http_code}\n" http://localhost:80/ || true
        echo "Sprawdzanie, czy proces Apache httpd działa w kontenerze Apache..."
        sudo docker compose exec apache ps aux | grep httpd | grep -v grep && echo "Proces Apache httpd znaleziony!" || echo "Proces Apache httpd NIE znaleziony!"
      continue-on-error: true

    - name: Czyszczenie usług Docker Compose
      if: always()
      run: |
        echo "Zatrzymywanie i usuwanie usług Docker Compose..."
        sudo docker compose down -v --rmi all || true
        echo "Czyszczenie zakończone."